package dev.silksong.launcher

import android.content.Context
import android.util.AttributeSet
import android.view.View
import android.widget.ImageView
import kotlin.math.roundToInt

/**
 * ImageView that resolves build-staged Steam artwork by resource name at
 * runtime. The launcher AAR can therefore compile without redistributing
 * Team Cherry artwork in git; CI/local Docker stages the official Steam CDN
 * files before the final APK resources are linked.
 *
 * Set android:tag to one of:
 *   launcher_hero, launcher_logo, ic_launcher
 */
class OfficialSteamAssetView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0,
) : ImageView(context, attrs, defStyleAttr) {

    /**
     * The staged hero drawable is attached after the first layout pass. A
     * wrap-content ImageView with no drawable can otherwise consume the very
     * large AT_MOST height supplied by a ScrollView, which makes its parent
     * hero frame fill almost the whole page and pushes every launcher control
     * below the fold.
     *
     * Give launcher_hero a deterministic wide height from the start. Once the
     * official drawable exists, use its intrinsic ratio; until then use the
     * standard Steam library-hero ratio (1920x620). No artwork is cropped or
     * regenerated by this measurement.
     */
    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
        if (tag?.toString()?.trim() == "launcher_hero") {
            val widthMode = View.MeasureSpec.getMode(widthMeasureSpec)
            val width = View.MeasureSpec.getSize(widthMeasureSpec)
            if (widthMode != View.MeasureSpec.UNSPECIFIED && width > 0) {
                val source = drawable
                val heightOverWidth = if (
                    source != null && source.intrinsicWidth > 0 && source.intrinsicHeight > 0
                ) {
                    source.intrinsicHeight.toFloat() / source.intrinsicWidth.toFloat()
                } else {
                    620f / 1920f
                }
                val targetHeight = (width * heightOverWidth).roundToInt().coerceAtLeast(1)
                val exactHeight = View.MeasureSpec.makeMeasureSpec(targetHeight, View.MeasureSpec.EXACTLY)
                super.onMeasure(widthMeasureSpec, exactHeight)
                return
            }
        }
        super.onMeasure(widthMeasureSpec, heightMeasureSpec)
    }

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        loadOfficialAsset()
    }

    private fun loadOfficialAsset() {
        val resourceName = tag?.toString()?.trim().orEmpty()
        if (resourceName.isEmpty()) return

        val type = if (resourceName == "ic_launcher") "mipmap" else "drawable"
        val resolved = resources.getIdentifier(resourceName, type, context.packageName)
        if (resolved != 0) {
            setImageResource(resolved)
            return
        }

        // Local/IDE builds can skip the network staging script. Keep the UI
        // usable without pretending the fallback is the official artwork.
        if (resourceName == "ic_launcher" || resourceName == "launcher_logo") {
            setImageResource(R.drawable.launcher_mark)
        }
    }
}
