package dev.silksong.launcher

import java.io.File
import java.io.IOException

/**
 * Verifies the Steamworks native ABI that IL2CPP generated for Silksong.
 *
 * Steamworks.NET P/Invoke calls are converted by IL2CPP into generated C/C++
 * containing the native entry-point names as string literals. The final
 * libil2cpp.so is intentionally linked with --allow-shlib-undefined, so a
 * missing Steam symbol otherwise survives the build and is only discovered
 * when the game tries to resolve it at runtime.
 *
 * This audit treats our Android libsteam_api.so as an ABI-compatible front end:
 * every Steam entry point generated by Silksong must be one we deliberately
 * export. The implementation behind achievement calls remains the launcher
 * JavaSteam bridge rather than Valve's desktop/Steam-client IPC.
 */
object SteamAbiAudit {

    data class Result(
        val required: Set<String>,
        val missing: Set<String>,
        val interfaceVersions: Set<String>,
    )

    private val symbolRegex = Regex(
        "(?:SteamAPI_[A-Za-z0-9_]+|SteamInternal_[A-Za-z0-9_]+|Steam_GetHSteamUserCurrent|SteamUserStats)"
    )
    private val interfaceRegex = Regex("STEAMUSERSTATS_INTERFACE_VERSION[0-9]{3}")

    /** Keep this in lock-step with steam_api_shim.c. */
    private val supported = setOf(
        "SteamAPI_Init",
        "SteamAPI_InitSafe",
        "SteamAPI_Shutdown",
        "SteamAPI_RunCallbacks",
        "SteamAPI_IsSteamRunning",
        "SteamAPI_ReleaseCurrentThreadMemory",
        "SteamAPI_GetHSteamUser",
        "SteamAPI_GetHSteamPipe",
        "Steam_GetHSteamUserCurrent",
        "SteamAPI_RestartAppIfNecessary",
        "SteamInternal_FindOrCreateUserInterface",
        "SteamInternal_CreateInterface",
        "SteamAPI_ManualDispatch_Init",
        "SteamAPI_ManualDispatch_RunFrame",
        "SteamAPI_ManualDispatch_GetNextCallback",
        "SteamAPI_ManualDispatch_FreeLastCallback",
        "SteamAPI_ManualDispatch_GetAPICallResult",
        "SteamAPI_SteamUserStats_v001",
        "SteamAPI_SteamUserStats_v002",
        "SteamAPI_SteamUserStats_v003",
        "SteamAPI_SteamUserStats_v004",
        "SteamAPI_SteamUserStats_v005",
        "SteamAPI_SteamUserStats_v006",
        "SteamAPI_SteamUserStats_v007",
        "SteamAPI_SteamUserStats_v008",
        "SteamAPI_SteamUserStats_v009",
        "SteamAPI_SteamUserStats_v010",
        "SteamAPI_SteamUserStats_v011",
        "SteamAPI_SteamUserStats_v012",
        "SteamAPI_SteamUserStats_v013",
        "SteamUserStats",
        "SteamAPI_ISteamUserStats_RequestCurrentStats",
        "SteamAPI_ISteamUserStats_SetAchievement",
        "SteamAPI_ISteamUserStats_StoreStats",
        "SteamAPI_ISteamUserStats_GetAchievement",
        "SteamAPI_ISteamUserStats_ClearAchievement",
        "SteamAPI_ISteamUserStats_GetAchievementAndUnlockTime",
        "SteamAPI_ISteamUserStats_GetNumAchievements",
        "SteamAPI_ISteamUserStats_GetAchievementName",
        "SteamAPI_ISteamUserStats_IndicateAchievementProgress",
        "SteamAPI_RegisterCallback",
        "SteamAPI_UnregisterCallback",
        "SteamAPI_RegisterCallResult",
        "SteamAPI_UnregisterCallResult",
    )

    fun inspect(cppDir: File): Result {
        val required = sortedSetOf<String>()
        val versions = sortedSetOf<String>()

        cppDir.walkTopDown()
            .filter { it.isFile && (it.extension == "cpp" || it.extension == "c" || it.extension == "h") }
            .forEach { file ->
                runCatching {
                    file.bufferedReader().useLines { lines ->
                        lines.forEach { line ->
                            symbolRegex.findAll(line).forEach { required += it.value }
                            interfaceRegex.findAll(line).forEach { versions += it.value }
                        }
                    }
                }.getOrElse { throw IOException("could not audit Steam ABI in $file", it) }
            }

        val missing = required.filterTo(sortedSetOf()) { it !in supported }
        return Result(required, missing, versions)
    }

    fun requireCompatible(cppDir: File) {
        val result = inspect(cppDir)
        val reportDir = cppDir.parentFile ?: cppDir
        runCatching {
            File(reportDir, "steam-abi-required.txt")
                .writeText(result.required.joinToString("\n", postfix = if (result.required.isEmpty()) "" else "\n"))
            File(reportDir, "steam-abi-interfaces.txt")
                .writeText(result.interfaceVersions.joinToString("\n", postfix = if (result.interfaceVersions.isEmpty()) "" else "\n"))
            File(reportDir, "steam-abi-missing.txt")
                .writeText(result.missing.joinToString("\n", postfix = if (result.missing.isEmpty()) "" else "\n"))
        }.onFailure {
            LauncherLog.log("Steam ABI audit: could not write diagnostic files: ${it.message}")
        }

        if (result.required.isEmpty()) {
            LauncherLog.log("Steam ABI audit: no Steam entry-point strings found in translated C++")
            return
        }

        LauncherLog.log(
            "Steam ABI audit: ${result.required.size} entry point(s), " +
                "interfaces=${result.interfaceVersions.ifEmpty { setOf("none discovered") }.joinToString()}"
        )
        LauncherLog.log("Steam ABI required: ${result.required.joinToString()}")

        if (result.missing.isNotEmpty()) {
            LauncherLog.log("Steam ABI MISSING: ${result.missing.joinToString()}")
            throw IOException(
                "translated Silksong requires unsupported Steamworks ABI entry point(s): " +
                    result.missing.joinToString()
            )
        }

        LauncherLog.log("Steam ABI audit: compatible with Android libsteam_api.so shim")
    }
}
